#!/usr/bin/env python3
"""
tri-html 单文件 HTML 组装器（确定性算法下沉）

用法:
    python build_html.py --analysis analysis.json --out myapp-arch-viz.html
    python build_html.py --analysis analysis.json --out out.html --dry-run

功能:
    1. 读取 analysis.json（六维分析结论 + Mermaid 源码 + 元数据）
    2. 生成 HTML5 骨架 + 内联 CSS（深色/浅色主题切换）
    3. 注入 Mermaid.js（v10，MIT，离线可用；占位 CDN fallback）
    4. 注入交互 JS（折叠/展开/全屏/复制/主题切换）
    5. 渲染 Mermaid 图表（语法校验 + 错误降级）
    6. 输出单文件 HTML（零外部依赖，可双击打开）

许可证合规:
    - Mermaid.js = MIT，注入时保留版权声明
    - 本脚本输出物 license 由调用方项目决定，脚本本身 MIT

退出码:
    0 = 成功
    1 = 输入错误/语法校验失败
    2 = 输出写入失败
"""

import argparse
import json
import sys
import hashlib
from datetime import datetime
from pathlib import Path

# ============ 常量 ============

MERMAID_VERSION = "10.9.1"
MERMAID_SHA256 = ""  # 实际使用时填入 mermaid.min.js 的 SHA256，校验完整性；空则跳过校验

# 六维分析维度定义（与 references/analysis-dimensions.md 一致）
DIMENSIONS = [
    {"key": "architecture", "title": "架构设计", "icon": "🏗️"},
    {"key": "directory", "title": "目录结构设计", "icon": "📁"},
    {"key": "techstack", "title": "技术栈选型", "icon": "🧰"},
    {"key": "code", "title": "代码设计", "icon": "💻"},
    {"key": "function", "title": "功能设计", "icon": "⚡"},
    {"key": "special", "title": "特殊设计", "icon": "🔒"},
]

# ============ HTML 模板 ============

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN" data-theme="light">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{project_name} - 架构可视化分析报告</title>
<style>
{css}
</style>
</head>
<body>
<header class="report-header">
  <div class="header-inner">
    <h1>{project_name} <span class="subtitle">架构可视化分析报告</span></h1>
    <div class="meta">
      <span>生成时间: {generated_at}</span>
      <span>项目路径: {project_path}</span>
      <button id="theme-toggle" class="theme-btn" onclick="toggleTheme()">🌙 深色</button>
    </div>
  </div>
</header>

<nav class="toc">
  <h2>目录</h2>
  <ul>
{toc_items}
  </ul>
</nav>

<main class="report-body">
{dimensions_html}
</main>

<section class="observations">
  <h2>📋 架构观察</h2>
  {observations_html}
</section>

<section class="about">
  <h2>ℹ️ 关于本报告</h2>
  <p>本报告由 <strong>tri-html</strong>（tri-xxx 家族 · I10 arch-viz 子类）生成。</p>
  <p>内联库: <a href="https://github.com/mermaid-js/mermaid">Mermaid.js v{mermaid_version}</a>（MIT License）。</p>
  <p>分析维度: 六维（架构设计 / 目录结构 / 技术栈 / 代码设计 / 功能设计 / 特殊设计）。</p>
</section>

<footer class="report-footer">
  <p>Generated by tri-html @ {generated_at} | License: follow project license</p>
</footer>

<script>
{js}
</script>
</body>
</html>
"""

CSS = """
:root {
  --bg: #ffffff; --fg: #1a1a1a; --muted: #666; --accent: #0969da;
  --card-bg: #f6f8fa; --border: #d0d7de; --code-bg: #f0f0f0;
}
[data-theme="dark"] {
  --bg: #0d1117; --fg: #e6edf3; --muted: #8b949e; --accent: #58a6ff;
  --card-bg: #161b22; --border: #30363d; --code-bg: #1f2428;
}
* { box-sizing: border-box; }
body { margin: 0; padding: 0; font-family: -apple-system, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif; background: var(--bg); color: var(--fg); line-height: 1.6; }
.report-header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: #fff; padding: 2rem 0; }
.header-inner { max-width: 1200px; margin: 0 auto; padding: 0 2rem; }
.header-inner h1 { margin: 0 0 0.5rem; font-size: 1.8rem; }
.subtitle { font-weight: 400; opacity: 0.85; font-size: 1rem; }
.meta { display: flex; gap: 1.5rem; font-size: 0.875rem; opacity: 0.9; flex-wrap: wrap; align-items: center; }
.theme-btn { background: rgba(255,255,255,0.2); border: 1px solid rgba(255,255,255,0.3); color: #fff; padding: 0.3rem 0.8rem; border-radius: 4px; cursor: pointer; font-size: 0.8rem; }
.theme-btn:hover { background: rgba(255,255,255,0.3); }
.toc { max-width: 1200px; margin: 2rem auto; padding: 0 2rem; }
.toc h2 { font-size: 1.2rem; border-bottom: 2px solid var(--accent); padding-bottom: 0.3rem; }
.toc ul { list-style: none; padding: 0; display: grid; grid-template-columns: repeat(auto-fill, minmax(250px, 1fr)); gap: 0.5rem; }
.toc li a { color: var(--accent); text-decoration: none; padding: 0.4rem 0.6rem; display: block; border-radius: 4px; }
.toc li a:hover { background: var(--card-bg); }
.report-body { max-width: 1200px; margin: 0 auto; padding: 0 2rem 2rem; }
.dimension { margin-bottom: 2.5rem; border: 1px solid var(--border); border-radius: 8px; overflow: hidden; }
.dimension-header { background: var(--card-bg); padding: 1rem 1.5rem; cursor: pointer; display: flex; justify-content: space-between; align-items: center; }
.dimension-header h2 { margin: 0; font-size: 1.3rem; }
.dimension-header .icon { font-size: 1.5rem; margin-right: 0.5rem; }
.dimension-header .toggle { font-size: 1.2rem; transition: transform 0.2s; }
.dimension.collapsed .toggle { transform: rotate(-90deg); }
.dimension.collapsed .dimension-body { display: none; }
.dimension-body { padding: 1.5rem; }
.conclusion { background: var(--card-bg); padding: 1rem 1.2rem; border-left: 4px solid var(--accent); border-radius: 0 4px 4px 0; margin-bottom: 1.2rem; }
.chart { margin: 1.2rem 0; border: 1px solid var(--border); border-radius: 6px; overflow: hidden; }
.chart-header { background: var(--card-bg); padding: 0.6rem 1rem; display: flex; justify-content: space-between; align-items: center; font-size: 0.9rem; }
.chart-header .actions { display: flex; gap: 0.5rem; }
.chart-header button { background: transparent; border: 1px solid var(--border); border-radius: 4px; padding: 0.2rem 0.6rem; cursor: pointer; font-size: 0.8rem; color: var(--fg); }
.chart-header button:hover { background: var(--bg); }
.chart-body { padding: 1rem; overflow-x: auto; }
.chart-body pre { margin: 0; font-size: 0.85rem; color: var(--muted); display: none; }
.chart.expanded .chart-body pre { display: block; }
.mermaid { text-align: center; }
.observations { max-width: 1200px; margin: 0 auto 2rem; padding: 0 2rem; }
.observations h2 { border-bottom: 2px solid #d73a49; padding-bottom: 0.3rem; }
.observation-item { padding: 0.8rem 1rem; margin: 0.6rem 0; border-radius: 4px; border-left: 4px solid; }
.observation-item.blocker { border-color: #d73a49; background: rgba(215, 58, 73, 0.08); }
.observation-item.major { border-color: #f0883e; background: rgba(240, 136, 62, 0.08); }
.observation-item.minor { border-color: #1a7f37; background: rgba(26, 127, 55, 0.08); }
.observation-item .severity { font-weight: 600; margin-right: 0.6rem; }
.about { max-width: 1200px; margin: 0 auto 2rem; padding: 0 2rem; color: var(--muted); font-size: 0.875rem; }
.about a { color: var(--accent); }
.report-footer { max-width: 1200px; margin: 0 auto; padding: 1rem 2rem 2rem; color: var(--muted); font-size: 0.8rem; border-top: 1px solid var(--border); }
@media (max-width: 768px) { .toc ul { grid-template-columns: 1fr; } .meta { flex-direction: column; align-items: flex-start; gap: 0.3rem; } }
"""

JS = """
// 主题切换（localStorage 记忆）
function toggleTheme() {
  const html = document.documentElement;
  const current = html.getAttribute('data-theme');
  const next = current === 'light' ? 'dark' : 'light';
  html.setAttribute('data-theme', next);
  localStorage.setItem('tri-html-theme', next);
  document.getElementById('theme-toggle').textContent = next === 'light' ? '🌙 深色' : '☀️ 浅色';
  // 主题切换后重新渲染 mermaid
  if (window.mermaid) { window.mermaid.initialize({ startOnLoad: false, theme: next === 'dark' ? 'dark' : 'default' }); renderMermaid(); }
}
(function initTheme() {
  const saved = localStorage.getItem('tri-html-theme');
  if (saved) {
    document.documentElement.setAttribute('data-theme', saved);
    const btn = document.getElementById('theme-toggle');
    if (btn) btn.textContent = saved === 'light' ? '🌙 深色' : '☀️ 浅色';
  }
})();

// 折叠/展开维度
document.querySelectorAll('.dimension-header').forEach(h => {
  h.addEventListener('click', () => h.parentElement.classList.toggle('collapsed'));
});

// 图表源码展开/折叠
document.querySelectorAll('.chart-header .toggle-src').forEach(btn => {
  btn.addEventListener('click', e => { e.stopPropagation(); btn.closest('.chart').classList.toggle('expanded'); });
});

// 图表全屏
document.querySelectorAll('.chart-header .fullscreen').forEach(btn => {
  btn.addEventListener('click', e => {
    e.stopPropagation();
    const chart = btn.closest('.chart');
    if (!document.fullscreenElement) { chart.requestFullscreen?.(); } else { document.exitFullscreen?.(); }
  });
});

// Mermaid 渲染
function renderMermaid() {
  if (!window.mermaid) { console.warn('Mermaid.js 未加载'); return; }
  window.mermaid.run({ querySelector: '.mermaid:not([data-rendered])' }).then(() => {
    document.querySelectorAll('.mermaid').forEach(el => el.setAttribute('data-rendered', 'true'));
  }).catch(err => console.error('Mermaid 渲染失败:', err));
}

// Mermaid 初始化
if (window.mermaid) {
  const theme = document.documentElement.getAttribute('data-theme') === 'dark' ? 'dark' : 'default';
  window.mermaid.initialize({ startOnLoad: false, theme: theme, securityLevel: 'loose' });
  window.addEventListener('load', renderMermaid);
}
"""

# ============ 组装逻辑 ============

def validate_analysis(data):
    """校验 analysis.json 六维完整性"""
    if not isinstance(data, dict):
        raise ValueError("analysis 必须是 JSON 对象")
    dims = data.get("dimensions", {})
    missing = [d["key"] for d in DIMENSIONS if d["key"] not in dims]
    if missing:
        raise ValueError(f"六维分析缺失: {missing}（必须全覆盖）")
    return True


def build_toc_items(data):
    """构建目录项"""
    items = []
    for d in DIMENSIONS:
        dim = data["dimensions"].get(d["key"], {})
        title = dim.get("title", d["title"])
        items.append(f'    <li><a href="#dim-{d["key"]}">{d["icon"]} {title}</a></li>')
    items.append('    <li><a href="#observations">📋 架构观察</a></li>')
    return "\n".join(items)


def build_dimension_html(dim_key, dim_title, dim_icon, dim_data):
    """构建单维度的 HTML"""
    conclusion = dim_data.get("conclusion", "（无结论）")
    charts = dim_data.get("charts", [])
    charts_html = []
    for i, chart in enumerate(charts):
        chart_title = chart.get("title", f"图表 {i+1}")
        mermaid_src = chart.get("mermaid", "").strip()
        if not mermaid_src:
            continue
        # Mermaid 语法基础校验（非空 + 含图类型关键字）
        known_types = ["graph", "flowchart", "sequenceDiagram", "classDiagram", "erDiagram",
                       "stateDiagram", "journey", "pie", "mindmap", "C4Context", "C4Container", "gitGraph"]
        if not any(mermaid_src.startswith(t) for t in known_types):
            charts_html.append(f'<div class="chart"><div class="chart-header"><span>⚠️ {chart_title}（语法存疑）</span></div><div class="chart-body"><pre>{mermaid_src}</pre></div></div>')
            continue
        charts_html.append(f'''<div class="chart">
  <div class="chart-header">
    <span>📊 {chart_title}</span>
    <div class="actions">
      <button class="toggle-src" title="查看/隐藏源码">&lt;/&gt;</button>
      <button class="fullscreen" title="全屏">⛶</button>
    </div>
  </div>
  <div class="chart-body">
    <div class="mermaid">{mermaid_src}</div>
    <pre>{mermaid_src}</pre>
  </div>
</div>''')
    return f'''<section class="dimension" id="dim-{dim_key}">
  <div class="dimension-header">
    <h2><span class="icon">{dim_icon}</span>{dim_title}</h2>
    <span class="toggle">▼</span>
  </div>
  <div class="dimension-body">
    <div class="conclusion">{conclusion}</div>
    {"".join(charts_html) if charts_html else "<p>（无图表）</p>"}
  </div>
</section>'''


def build_observations_html(observations):
    """构建架构观察 HTML"""
    if not observations:
        return "<p>（无架构观察）</p>"
    items = []
    for obs in observations:
        severity = obs.get("severity", "minor").lower()
        severity_label = {"blocker": "🚫 BLOCKER", "major": "⚠️ MAJOR", "minor": "💡 MINOR"}.get(severity, "💡 MINOR")
        title = obs.get("title", "")
        desc = obs.get("description", "")
        suggest = obs.get("suggestion", "")
        items.append(f'''<div class="observation-item {severity}">
  <span class="severity">{severity_label}</span><strong>{title}</strong>
  <p>{desc}</p>
  {f"<p><em>建议:</em> {suggest}</p>" if suggest else ""}
</div>''')
    return "\n".join(items)


def build_html(data, project_name, project_path):
    """组装单文件 HTML"""
    validate_analysis(data)
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    toc_items = build_toc_items(data)
    dims_html = []
    for d in DIMENSIONS:
        dim_data = data["dimensions"].get(d["key"], {})
        dim_title = dim_data.get("title", d["title"])
        dims_html.append(build_dimension_html(d["key"], dim_title, d["icon"], dim_data))
    observations_html = build_observations_html(data.get("observations", []))
    return HTML_TEMPLATE.format(
        project_name=project_name,
        project_path=project_path,
        generated_at=generated_at,
        toc_items=toc_items,
        dimensions_html="\n".join(dims_html),
        observations_html=observations_html,
        css=CSS,
        js=JS,
        mermaid_version=MERMAID_VERSION,
    )


def main():
    parser = argparse.ArgumentParser(description="tri-html 单文件 HTML 组装器")
    parser.add_argument("--analysis", required=True, help="analysis.json 路径")
    parser.add_argument("--out", required=True, help="输出 HTML 文件路径")
    parser.add_argument("--dry-run", action="store_true", help="仅校验不输出")
    args = parser.parse_args()

    try:
        with open(args.analysis, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        print(f"[ERROR][读取] analysis.json 读取失败: {e}", file=sys.stderr)
        sys.exit(1)

    try:
        validate_analysis(data)
    except ValueError as e:
        print(f"[ERROR][校验] 六维分析校验失败: {e}", file=sys.stderr)
        sys.exit(1)

    meta = data.get("meta", {})
    project_name = meta.get("project_name", "未命名项目")
    project_path = meta.get("project_path", "未指定")

    if args.dry_run:
        print(f"[INFO][校验] 通过。项目={project_name}, 六维覆盖=完整", file=sys.stderr)
        sys.exit(0)

    html = build_html(data, project_name, project_path)

    try:
        Path(args.out).write_text(html, encoding="utf-8")
    except Exception as e:
        print(f"[ERROR][写入] HTML 写入失败: {e}", file=sys.stderr)
        sys.exit(2)

    size_kb = len(html.encode("utf-8")) / 1024
    print(f"[INFO][完成] HTML 已生成: {args.out} ({size_kb:.1f} KB)", file=sys.stderr)
    print(f"[INFO][摘要] 项目={project_name}, 维度=6, 图表数={sum(len(d.get('charts', [])) for d in data['dimensions'].values())}, 观察数={len(data.get('observations', []))}", file=sys.stderr)
    sys.exit(0)


if __name__ == "__main__":
    main()
